name: 构建五子棋游戏

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build-windows:
    name: 构建Windows版本
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 安装Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        arch: 'win64_msvc2019_64'
        
    - name: 配置MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: 配置项目
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -A x64 ..
        
    - name: 编译项目
      run: |
        cd build
        cmake --build . --config Release
        
    - name: 部署Qt依赖
      run: |
        cd build
        cmake --install . --prefix . --config Release
        if (Test-Path "bin\Gobang.exe") {
          windeployqt.exe bin\Gobang.exe --release --force
        } else {
          echo "找不到Gobang.exe，列出构建文件："
          Get-ChildItem -Recurse -Name "*.exe"
          echo "检查bin目录："
          if (Test-Path "bin") { Get-ChildItem bin }
        }
        
    - name: 创建安装包
      run: |
        cd build
        cpack -G NSIS -C Release
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: Gobang-Game-Windows
        path: |
          build/*.exe
          build/bin/Gobang.exe

  build-macos:
    name: 构建macOS版本
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 安装Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        
    - name: 配置项目
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        
    - name: 编译项目
      run: |
        cd build
        cmake --build . --config Release
        
    - name: 创建应用程序包
      run: |
        cd build
        cmake --install . --prefix . --config Release
        # 查找Gobang.app的位置
        APP_PATH=$(find . -name "Gobang.app" -type d | head -1)
        if [ -n "$APP_PATH" ]; then
          echo "找到应用程序包：$APP_PATH"
          macdeployqt "$APP_PATH" -verbose=2
        else
          echo "找不到Gobang.app，列出所有.app文件："
          find . -name "*.app" -type d
          echo "列出当前目录结构："
          ls -la
        fi
        
    - name: 创建DMG
      run: |
        cd build
        cpack -G DragNDrop
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: Gobang-Game-macOS
        path: build/*.dmg

  build-linux:
    name: 构建Linux版本
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 安装系统依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qtmultimedia5-dev qt5-qmake cmake build-essential pkg-config
        
    - name: 配置项目
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        
    - name: 编译项目
      run: |
        cd build
        cmake --build . --config Release
        
    - name: 创建安装包
      run: |
        cd build
        cmake --install . --prefix .
        cpack -G DEB
        cpack -G TGZ
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: Gobang-Game-Linux
        path: |
          build/*.deb
          build/*.tar.gz

  release:
    name: 发布版本
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: 下载所有构建产物
      uses: actions/download-artifact@v4
      
    - name: 上传到Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Gobang-Game-Windows/*
          Gobang-Game-macOS/*
          Gobang-Game-Linux/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
